### ISSUE TITLE
AttributeError: 'TFModel' object has no attribute 'model_dir'

### ISSUE THREAD

**Issue by Sarajvega** [lobe/flask-server#6]
There is a path error in the latest version. 

**The error:**
```
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    TF_MODEL = TFModel(ASSETS_PATH)
  File "/Users/ada/Desktop/Dev/capstone/flask-server/tf_model_helper.py", line 41, in __init__
    self.model = tf.saved_model.load(tags=self.signature.get("tags"), export_dir=self.model_dir)
AttributeError: 'TFModel' object has no attribute 'model_dir'
```

To solve
Line 41 in tf_model_helper.py should be:
`self.model = tf.saved_model.load(tags=self.signature.get("tags"), export_dir=self.model_path)`

Which leads to another issue in `tf_model_help.py`: 
remove `fetches` from params of process_output() function. 

I would also recommend: 
In app.py turn Debug mode to False. Else it seems to restart the app.

**Comment by GarimaSarangal** [comment]
Hi @Sarajvega! Thank you reporting the bugging. We have pushed new changes to solve the model load and process output function call. We intent to make the flask server repository ready to develop and keeping the debug mode True will make new changes readily available. 

Closing this bug for now. Please reopen or create new bug if any issues.
